In [36]:
# importing libraries
import torch
import tiktoken
import torch.nn as nn
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [11]:
# read the text file
def read_text_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        text = file.read()
    return text

In [23]:
# feeding the text and cleaning it
file_path = 'training_text.txt'
text = read_text_file(file_path)

text = text.strip("\ufeff")
text = text.replace("\n", " ")

In [29]:
# length of text
print(len(text))
print(text[:100])

In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in


In [62]:
# checking all the characters used in the text
char = sorted(list(set(text)))
vocab_size = len(char)
print(''.join(char))
print(vocab_size)

 !$()*,-.0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXY[]abcdefghijklmnopqrstuvwxyzçéêô —‘’“”…
86


In [20]:
# bringing in tiktoken's tokenizer

# THIS WILL NOT WORK

enc = tiktoken.get_encoding("gpt2")
enc.n_vocab

50257

In [25]:
# testing with encoding and decoding; it works now, but note that we only have
# a vocab_size of 85
encode = enc.encode("hello")
print(encode)
enc.decode(encode)

encode1 = enc.encode(text[:100])
print(encode1)
enc.decode(encode1)

[31373]
[818, 616, 7099, 290, 517, 8826, 812, 616, 2988, 2921, 502, 617, 5608, 326, 314, 447, 247, 303, 587, 6225, 625, 287]


'In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in'

In [72]:
# hence we need to tokenize the vocab ourselves
stoi = { ch:i for i, ch in enumerate(char)}
itos = { i:ch for i, ch in enumerate(char)}

def encode(str):
    return [stoi[c] for c in str]

def decode(str):
    return "".join([itos[c] for c in str])

foo = encode("foo")
print(foo)
print(decode(foo))

[54, 63, 63]
foo


In [33]:
# now encoding the entire text
data = torch.tensor(enc.encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:500])

torch.Size([71784]) torch.int64
tensor([  818,   616,  7099,   290,   517,  8826,   812,   616,  2988,  2921,
          502,   617,  5608,   326,   314,   447,   247,   303,   587,  6225,
          625,   287,   616,  2000,  1683,  1201,    13,   220,   564,   250,
        28877,   345,  1254,   588, 26816,  2687,    11,   447,   251,   339,
         1297,   502,    11,   564,   250,  3137,  3505,   326,   477,   262,
          661,   287,   428,   995,  4398,   447,   247,    83,   550,   262,
        13391,   326,   345,   447,   247,   303,   550,    13,   447,   251,
          220,   679,  1422,   447,   247,    83,   910,   597,   517,    11,
          475,   356,   447,   247,   303,  1464,   587, 23708,  1316, 43058,
          287,   257, 10395,   835,    11,   290,   314,  7247,   326,   339,
         4001,   257,  1049,  1730,   517,   621,   326,    13,   554, 12921,
           11,   314,   447,   247,    76, 19514,   284, 11515,   477,  2553,
        43547,    11,   257,  79

In [34]:
# splitting data into training data and validation data
n = int(0.9*len(data))
train = data[:n]
val = data[n:]

In [35]:
# setting up block size
block_size = 8
train[:block_size + 1]

tensor([ 818,  616, 7099,  290,  517, 8826,  812,  616, 2988])

In [67]:
# setting batch size
batch_size = 4

# function for getting a batch of random blocks within data, set my batch_size
def get_batch(split):
    if split == "train":
        data = train
    else:
        data = val

    ix = torch.randint(len(data) - batch_size, (batch_size,))
    x = torch.stack([data[i:i + block_size] for i in ix])
    y = torch.stack([data[i + 1: i + block_size + 1] for i in ix])
    
    return x, y

In [68]:
# collecting inputs and targets from the training data
# targets used for creating the loss function later on
xb, yb = get_batch("train")

print(xb)
print(yb)

tensor([[ 1541,  6590, 10802,   286,   262,  3715,    13,   220],
        [  835,   284,  1194,  9082,    11,   281, 35639, 37968],
        [  262,  2479,   286, 38741,   290,   379,   262,  2176],
        [  607,  6576,    11,   290,  2063,   281,  1711,  1568]])
tensor([[ 6590, 10802,   286,   262,  3715,    13,   220,   317],
        [  284,  1194,  9082,    11,   281, 35639, 37968,   286],
        [ 2479,   286, 38741,   290,   379,   262,  2176,  2589],
        [ 6576,    11,   290,  2063,   281,  1711,  1568,    11]])


In [61]:
# class for the language model
class BigramLM(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, inputs, targets):
        logits = self.token_embedding_table(inputs) # batch, time, channel tensor

        return logits
    

In [64]:
model = BigramLM(vocab_size)

output = model(xb, yb)

print(output.shape)

IndexError: index out of range in self